"""add views and shortlist_count to service_listings

Revision ID: 610966291116
Revises: 
Create Date: 2025-05-12 15:39:12.110962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610966291116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_listings') as batch_op:
        batch_op.add_column(
            sa.Column('views', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('shortlist_count', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_listings', schema=None) as batch_op:
        batch_op.drop_column('shortlist_count')
        batch_op.drop_column('views')

    # ### end Alembic commands ###
